### ISSUE TITLE
[Bug] Parabolic doesn't download subtitles

### ISSUE THREAD

**Issue by mbridon** [NickvisionApps/Parabolic#1545]
**Describe the bug**
Launching Parabolic to download a video, it doesn't download the subtitles. 😞 

**Describe the expected result**
The subtitles should be downloaded along with the video.

**URL**
https://www.bbc.co.uk/iplayer/episode/m001sx3h/doctor-who-specials-1-the-star-beast

In Parabolic, when I add the URL for download, I'm shown this:

<img width="850" height="650" alt="Image" src="https://github.com/user-attachments/assets/281d995f-cb67-4d09-b9b0-caa842172390" />

Clicking on "Sous-titres" (French for "subtitles"), I see this:

<img width="850" height="650" alt="Image" src="https://github.com/user-attachments/assets/7f0f1f01-2227-4cbe-8bf0-126e962a862c" />

Parabolic can't find the subtitles. 😕 

However, I know for a fact there are subtitles for this specific video, because if I use the [`get_iplayer` tool](https://github.com/get-iplayer/get_iplayer) it can download them. 😕 

**Download Options**
I didn't configure any option, just using the defaults.

**App Version**
- [x] GNOME nightly on GNOME OS
    - [x] Flatpak

Version Number: 2025.11.1

**Additional context**
You need to be in the UK for the URL to let you access, or alternatively use a VPN with a server in the UK.

**Comment by nlogozzo** [comment]
Please update to the latest beta: https://github.com/NickvisionApps/Parabolic/releases/tag/2026.2.0-beta1-p1

This should be fixed in there. Let me know

**Comment by mbridon** [comment]
Sorry, but I still can't download the subtitles with the latest beta version you linked to. 😞

**Comment by nlogozzo** [comment]
Did it give you the `--compact-options` error?. If so, please wait and update to try: https://github.com/NickvisionApps/Parabolic/releases/tag/2026.2.0

**Comment by mbridon** [comment]
Not knowing this option, I have no idea if it gave it to me or not 🤷 

I'll wait and try to update then.

**Comment by mbridon** [comment]
So I updated the app from Flathub, now I have 2026.2.0, and yet:

<img width="569" height="515" alt="Image" src="https://github.com/user-attachments/assets/75231f0a-0f03-403c-99bb-65dd7d46101e" />

**Comment by mbridon** [comment]
Of course the `get_iplayer` tool is Perl, and me being a Python hacker I wasn't able to understand how it even downloads the subtitles 😞

**Comment by nlogozzo** [comment]
This is for BBC? Maybe `yt-dlp` doesn't support subtitles from it. Let me check.

**Comment by nlogozzo** [comment]
https://github.com/yt-dlp/yt-dlp/issues/656#issuecomment-894867089
https://github.com/yt-dlp/yt-dlp/issues/11095

https://github.com/yt-dlp/yt-dlp/issues?q=is%3Aissue%20state%3Aopen%20bbc%20subtitle

There are various issues with yt-dlp where it doesn't seem they properly support the iplayer used by bbc

**Comment by nlogozzo** [comment]
We can try building `get_iplayer` support into Parabolic but that'll be a feature request, and I have no timeline on how long that would take.
