### ISSUE TITLE
Prefer AV1 Codec is not downloading in AV1

### ISSUE THREAD

**Issue by DartDeaDia** [NickvisionApps/Parabolic#711]
If turn on the Prefer AV1 Codec option, in any video the codec is VP9, but not AV1

<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/40b76e61-5f11-412a-84d4-989dbf14cbbd" width="600">

<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/2213cc68-14e8-49bf-9052-2265ceb28bb1" width="500">
<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/47f16aa0-eaa7-48e8-9853-83bfb01f5b34" width="500">
<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/64258b85-7614-41fe-9486-9dbff89ee059" width="500">
<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/235b722c-46c4-4dfb-bf7b-fd19ac0c0f67" width="500">

I thought maybe they originally are using VP9 codec, but from the tested videos, only the [CHARGE - Blender Open Movie](https://youtu.be/UXqq0ZvbOnk?si=W8pzR4Rur2wnjuR0) is originally using VP9 codec

<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/1b9b2530-49eb-4069-afc0-8b048ea37cbc" width="500">

All other videos are using AV1, so what's the problem?

<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/86aa894a-c8d5-4dbb-967a-83ec9e107f24" width="500">
<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/c2e7f9cc-6fb7-44b0-badd-8ce7347eebfd" width="500">
<img src="https://github.com/NickvisionApps/Parabolic/assets/122628420/22d58057-4598-44d7-9495-28325c899d31" width="500">

**Comment by tazihad** [comment]
facing same problem

**Comment by nlogozzo** [comment]
@tazihad @DartDeaDia Should be fixed in this beta release: https://github.com/NickvisionApps/Parabolic/releases/tag/2023.12.0-beta2

**Comment by tazihad** [comment]
@nlogozzo please reopen this issue. av1 still not downloading. It's downloading vp9 codec.
[This video](https://www.youtube.com/watch?v=NkonYfn5wMQ&pp=ygUIYXYxIHRlc3Q%3D) is downloaded with vp9 codec even if **prefer av1** selected.
```
Resolution: 3840 x 2160
Aspect ratio: 1.77778
Format: vp9
Bitrate: 0 kbps
Frames per second: 59.941463
Selected codec: vp9
```

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
