### ISSUE TITLE
(FLATPAK) Downloading videos from youtube gives HTTP Error 403: Forbidden 

### ISSUE THREAD

**Issue by cassiofb-dev** [NickvisionApps/Parabolic#790]
Hi, first of all thanks for this amazing app.

I'im trying to download a video but its giving me "HTTP Error 403: Forbidden" as the title says. Here is the some links I tried:

- https://www.youtube.com/watch?v=Ezrbyf6t9mY
- https://www.youtube.com/watch?v=dQw4w9WgXcQ
- https://www.youtube.com/watch?v=vS2SIGF3qhk

I'm using flatpak version with the version 2024.5.0. Here what the full log says:
```txt
[youtube] Extracting URL: https://www.youtube.com/watch?v=Ezrbyf6t9mY
[youtube] Ezrbyf6t9mY: Downloading webpage
[youtube] Ezrbyf6t9mY: Downloading ios player API JSON
[youtube] Ezrbyf6t9mY: Downloading android player API JSON
[youtube] Ezrbyf6t9mY: Downloading player 38c5c1c9
WARNING: [youtube] Ezrbyf6t9mY: nsig extraction failed: You may experience throttling for some formats
         n = ddCxCaaReDkAUEmJ8y ; player = https://www.youtube.com/s/player/38c5c1c9/player_ias.vflset/en_US/base.js
WARNING: [youtube] Ezrbyf6t9mY: nsig extraction failed: You may experience throttling for some formats
         n = 9Fa67iMtZp8_frhSXH ; player = https://www.youtube.com/s/player/38c5c1c9/player_ias.vflset/en_US/base.js
[youtube] Ezrbyf6t9mY: Downloading m3u8 information
[info] Ezrbyf6t9mY: Downloading 1 format(s): 243+251
ERROR: unable to download video data: HTTP Error 403: Forbidden
```

**Comment by cassiofb-dev** [comment]
Update: This only happens when I select WEBM. MP4 and OPUS are working fine.

**Comment by ozky84** [comment]
Same here i have same problem

**Comment by cassiofb-dev** [comment]
I think this issue can be related: https://github.com/yt-dlp/yt-dlp/issues/10046

**Comment by cassiofb-dev** [comment]
Hi @nlogozzo , good night!

This is what yt-dlp guy said: https://github.com/yt-dlp/yt-dlp/issues/10046#issuecomment-2263172549
Do you think its nice to leave this opened so that people dont open again and can see it or its better to close it?

**Comment by nlogozzo** [comment]
Well the purposed solution on that comment was actually merged and released in yt-dlp 2024.08.01 . So I will test with the latest version and see

**Comment by nlogozzo** [comment]
This is fixed in the C++ branch

**Comment by ozky84** [comment]
I want to ask as you fixed this in c++ branch, how long time it will take you will release it?
as this main branch users will face this issue still...
Or can you fix it in this main branch?

**Comment by ozky84** [comment]
> > how long time it will take you will release it?
> 
> Once it's ready. I will be working all day today and tomorrow to try and get that to happen by the weekend.

Good nice thanks, take your time no need to hurry too much...

**Comment by ozky84** [comment]
Can you build testing version flatpak of that c++ branch?
Flatpak have beta repo available...

**Comment by nlogozzo** [comment]
> Can you build testing version flatpak of that c++ branch?
> Flatpak have beta repo available...
> 

I have one more feature left to implement and i will be releasing a beta today.

**Comment by ozky84** [comment]
Thanks, i just looked you have early morning in USA, I'm from Finland here is afternoon 13.37 clock time...
Take your time no need to hurry too much thanks...

**Comment by nlogozzo** [comment]
> Thanks, i just looked you have early morning in USA, I'm from Finland here is afternoon 13.37 clock time...
> Take your time no need to hurry too much thanks...

I'm actually on vacation in Italy this week so it's 12:52 PM here :)

**Comment by ozky84** [comment]
Nice good, 😂

**Comment by nlogozzo** [comment]
@ozky84 https://github.com/NickvisionApps/Parabolic/actions/runs/10613682340

In the meantime, you can download the gnome flatpak file from this build. This build contains all features except keyring management (which is the one feature i still have to implement. 

When you download the zip extract it and then you can run in the terminal `flatpak install org.nickvision.tubeconverter.flatpak` (or whatever the name of the file was) and run it with `flatpak run org.nickvision.tubeconverter//master`

**Comment by ozky84** [comment]
I noticed qt version can't add txt cookies file, there is only option export from browser?

**Comment by nlogozzo** [comment]
> I noticed qt version can't add txt cookies file, there is only option export from browser?

Both versions (GNOME and QT) no longer support uploading txt files for cookies but instead will do this process for you automatically from just selecting the browser that you would like to use.

Is the browser you usennot available from the list?

**Comment by ozky84** [comment]
I have Get cookies.txt LOCALLY  extension in Chrome...
This may not be good idea as Flatpak have some limitations
Same is with Fdm free download manager...

https://github.com/flathub/org.freedownloadmanager.Manager/issues/1

**Comment by ozky84** [comment]
I get this with Chrome and Parabolic preview:
The url provided is invalid or unable to be reached. Check the url, the authentication used, and the selected browser for cookies in settings.

**Comment by nlogozzo** [comment]
Did you select `Chrome` in the `Cookies from Browser` setting in Preferences?

If that still doesn't work, then I will add the option to manually upload cookies file again.

**Comment by ozky84** [comment]
Yes

**Comment by ozky84** [comment]
> If I can ask, what website are you trying to download from?

Youtube...there is some age limited videos Finntop5 make in Finnish language videos, not mean adult content...

**Comment by nlogozzo** [comment]
Ok...i thought yt-dlp has built-in getting around age limited without needed cookies...but could be wrong...will investigate and get back to you!

**Comment by ozky84** [comment]
Yeah thanks so much Nick :)
I do testing lot i'm in Mageia Linux qa team testing  packages goes to updates, also do Finnish translations :)

**Comment by nlogozzo** [comment]
@ozky84 https://github.com/NickvisionApps/Parabolic/actions/runs/10649311565

this build has the update that restores the option to upload a cookies file when running via flatpak/snap. You will no longer see the cookies browser option either, since, well, it doesn't work on flatpak.

Another question: Does the app crash when you close the preferences dialog?

**Comment by ozky84** [comment]
No it don't crash if close preferences dialog.

**Comment by ozky84** [comment]
No it don't crash if close preferences dialog.

**Comment by ozky84** [comment]
I noticed qt version get big cpu leak, 4 cores takes 100% usage...

**Comment by nlogozzo** [comment]
> I noticed qt version get big cpu leak, 4 cores takes 100% usage...

That's ffmpeg when downloading most likely. Does it go back to normal after a download?

**Comment by nlogozzo** [comment]
> No it don't crash if close preferences dialog.

Also, I was talking about the GNOME version. It's fully featured ou can use that now too.

**Comment by ozky84** [comment]
> > No it don't crash if close preferences dialog.
> 
> Also, I was talking about the GNOME version. It's fully featured ou can use that now too.

Yes it will crash when close settings, also it forget all settings have changed when it crash.

**Comment by nlogozzo** [comment]
> > > No it don't crash if close preferences dialog.
> > 
> > Also, I was talking about the GNOME version. It's fully featured ou can use that now too.
> 
> Yes it will crash when close settings, also it forget all settings have changed when it crash.

Ok that's the last thing for me to fix and then I can release the update!

**Comment by nlogozzo** [comment]
Parabolic [V2024.9.0-beta1](https://github.com/NickvisionApps/Parabolic/releases/tag/2024.9.0-beta1) is here with a fix for this issue!

Please follow the install instructions on the page to test it out :)
